import { PERMISSIONS } from '../../src/common/constants/permissions.js';
import { AppRole } from '../../src/common/constants/roles.js';

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [AppRole.SUPER_ADMIN]: ['*'],

  [AppRole.ADMIN]: [
    PERMISSIONS.USERS.READ,
    PERMISSIONS.USERS.CREATE,
    PERMISSIONS.USERS.UPDATE,
    PERMISSIONS.USERS.DELETE,

    PERMISSIONS.ROLES.READ,

    PERMISSIONS.PERMISSIONS.READ,

    PERMISSIONS.ANALYTICS.READ,

    PERMISSIONS.SYSTEM.MANAGE,
  ],

  [AppRole.MODERATOR]: [
    PERMISSIONS.USERS.READ,

    PERMISSIONS.POSTS.DELETE,

    PERMISSIONS.COMMENTS.DELETE,

    PERMISSIONS.STORIES.DELETE,

    PERMISSIONS.REELS.DELETE,
  ],

  [AppRole.CREATOR]: [
    PERMISSIONS.POSTS.CREATE,
    PERMISSIONS.POSTS.UPDATE,

    PERMISSIONS.VIDEOS.UPLOAD,

    PERMISSIONS.STREAMS.START,
    PERMISSIONS.STREAMS.END,

    PERMISSIONS.STORIES.CREATE,

    PERMISSIONS.REELS.CREATE,
  ],

  [AppRole.USER]: [
    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,

    PERMISSIONS.POSTS.CREATE,

    PERMISSIONS.COMMENTS.CREATE,

    PERMISSIONS.CHAT.WRITE,

    PERMISSIONS.UPLOADS.CREATE,
  ],
};
