// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr2e3KIGxO2QYR4HPkB5nnyxBXRx9ZAnM',
    appId: '1:869520328580:web:bfc4aa4957ef38b9e2ffd1',
    messagingSenderId: '869520328580',
    projectId: 'zikre-kidusan',
    authDomain: 'zikre-kidusan.firebaseapp.com',
    storageBucket: 'zikre-kidusan.firebasestorage.app',
    measurementId: 'G-K6GQF33W11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc0pfq0gwUw-YgncWPoyXmHxb5mnASHHE',
    appId: '1:869520328580:android:53f2ed349adb3d25e2ffd1',
    messagingSenderId: '869520328580',
    projectId: 'zikre-kidusan',
    storageBucket: 'zikre-kidusan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu64dljK0N18r_PX8CE7OkJ4uvarMskWg',
    appId: '1:869520328580:ios:50c6ceee74741a84e2ffd1',
    messagingSenderId: '869520328580',
    projectId: 'zikre-kidusan',
    storageBucket: 'zikre-kidusan.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu64dljK0N18r_PX8CE7OkJ4uvarMskWg',
    appId: '1:869520328580:ios:50c6ceee74741a84e2ffd1',
    messagingSenderId: '869520328580',
    projectId: 'zikre-kidusan',
    storageBucket: 'zikre-kidusan.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr2e3KIGxO2QYR4HPkB5nnyxBXRx9ZAnM',
    appId: '1:869520328580:web:da970f91d246984ce2ffd1',
    messagingSenderId: '869520328580',
    projectId: 'zikre-kidusan',
    authDomain: 'zikre-kidusan.firebaseapp.com',
    storageBucket: 'zikre-kidusan.firebasestorage.app',
    measurementId: 'G-BDHB9RMWD9',
  );
}
